[build-system]
requires = ["setuptools"]
build-backend = "setuptools.build_meta"

[project]
name = "yt-content-monetization"
version = "0.1.0"
description = "YouTube revenue modeling project"
authors = [{name = "Geetha"}]
dependencies = []

[tool.setuptools]
packages = ["src"]
